site_name: Notas Musicais
      repo_url: https://github.com/vandercast/notas-musicais
repo_name: vandercast/notas-musicais
edit_uri: tree/master/docs
theme:
  name: material
  language: pt-BR
  locale: pt_BR
  logo: assets/logo.png
  favicon: assets/logo.png
markdown_extensions:
  - attr_list

extra_css:
  - stylesheets/extra.css